version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  cartdb:
    container_name: cartdb
    restart: always
    ports:
      - "6379:6379"

  discountdb:
    container_name: discountdb
    environment:
      - MYSQL_DATABASE=discountdb
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=MySql!1
      - MYSQL_ROOT_PASSWORD=admin
    restart: always
    ports:
      - "3306:3306"
  
  orderdb:
    container_name: orderdb
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SqlServer!1
      - MSSQL_PID=Developer
    restart: always
    ports:
      - "1433:1433"
   
  adminer:
    container_name: adminer
    environment:
      ADMINER_DEFAULT_SERVER: discountdb
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - adminer_data:/root/.adminer
    
  portainer:
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
    depends_on:
      - catalogdb
    ports:
      - "8000:80"

  cart.api:
    container_name: cart.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=cartdb:6379"
      - "GrpcSettings:DiscountUrl=discount.grpc"
      #- "EventBusSettings:HostAddress=rabbitmq://guest:guest@rabbitmq:5672"
    depends_on:
      - cartdb
      #- rabbitmq
    ports:
      - "8001:80"

  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=server=discountdb;port=3306; user Id=admin; password = MySql!1; database = discountdb;"
    depends_on:
      - discountdb
    ports:
      - "8002:80"


  discount.grpc:
    container_name: discount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=server=discountdb;port=3306; user Id=admin; password = MySql!1; database = discountdb;"
    depends_on:
      - discountdb
    ports:
      - "8003:80"

  order.api:
    container_name: order.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:OrderConnectionString=Server=orderdb;Database=orderdb;User Id=sa;Password=SqlServer!1;TrustServerCertificate = True;"
    depends_on: 
      - orderdb
    ports:
      - "8004:80"

